### ISSUE TITLE
Debian package: update dependency in d/control

### ISSUE THREAD

**Issue by tenzap** [apache/netbeans-nbpackage#39] opened 2023-08-05 05:33 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

apache-netbeans package recommends "java11-sdk"

This package is not available in bookworm, leaving the dependency as unsatisfied and causing some problems when installing the package (it wants to pull that specific version while bookworm now defaults to java17".

I would suggest to use this instead:
```
Recommends: default-jdk (>= 2:1.11~)
```
or 
```
Depends: default-jdk (>= 2:1.11~)
```

It would probably make it more portable.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian Bookworm (12.1)

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2023-08-05 07:53
> This package is not available in bookworm, leaving the dependency as unsatisfied

https://packages.debian.org/bookworm/java11-sdk

The virtual package was a deliberate choice. And as it's a recommends, rather than depends, should still be possible to work around if it cannot be satisfied. Not sure what's going on here? Is it a new Debian install or an upgraded one?

**Comment by neilcsmith-net** [comment] 2023-08-05 10:03
As far as I know, default-jdk is not a virtual package - it depends on the default JDK. Consider this 

https://packages.debian.org/sid/java11-sdk

Installing any of those should satisfy the virtual recommends. That would be different to recommending default-jdk. If you need to run on a specific JDK that provides the token, make sure you install it first or just ignore the recommends.

This is a fallback option when NBPackage is used without a local bundled runtime JDK. I'd recommend using the community installers at https://www.codelerity.com/netbeans/ to take OS resolution out of the equation. There's no perfect solution for the fallback, but IMO what we have now is a better option.

**Comment by neilcsmith-net** [comment] 2023-08-05 11:03
But on Sid it would recommend install of Java 17, even if you already had Java 11, 19 or 20 installed I believe.

There's also no guarantees that the JDK it runs on is the desired or installed one. I can't remember if the default JDK gets changed by package install, and if it does that might not be desired either.

Sorry, I don't agree this is the right approach. If anything I'd remove the recommends if it causes problems. We should document these pre-requirements more clearly. I also think we should be clearer about the differences between considering the ASF and JDK-bundling installers, and why the latter being self contained can offer a more trouble free experience.

**Comment by mbien** [comment] 2023-08-05 20:34
> But in my sources.list I had also older versions of Debian.

@tenzap this can cause issues by creating a frankenstein distribution, unless you are very careful by setting the source priorities in the apt preferences.

> IIRC, because of java11-sdk it wanted to install java11 from an older distribution 

@tenzap ... yeah. Which may or may not work on bookworm since it doesn't expect a bullseye package to be there.



> On a clean distro install without older package sources, this should usually do the right thing, without overriding those who have installed a different package?

@neilcsmith-net i have an old virtualbox image which is periodically updated since debian 10.x which is now on bookworkm and tried the following:
 - tested the deb installer and it worked (openjdk-17 was installed)
 - now i uninstalled all `openjdk-*` and `java*` packages and tried again:
```
sudo apt install ./apache-netbeans_18-1_all.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'apache-netbeans' instead of './apache-netbeans_18-1_all.deb'
The following additional packages will be installed:
  ca-certificates-java default-jdk default-jdk-headless default-jre default-jre-headless java-common openjdk-17-jdk openjdk-17-jdk-headless openjdk-17-jre
  openjdk-17-jre-headless
Suggested packages:
  openjdk-17-demo openjdk-17-source visualvm fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  apache-netbeans ca-certificates-java default-jdk default-jdk-headless default-jre default-jre-headless java-common openjdk-17-jdk openjdk-17-jdk-headless
  openjdk-17-jre openjdk-17-jre-headless
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 120 MB/526 MB of archives.
After this operation, 276 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
and it resolves the dependency as `opendjk-17` which is fine

**Comment by neilcsmith-net** [comment] 2023-08-07 11:21
@mbien thanks for confirmation.  As well as my main Ubuntu 22.04 systems, I test the .deb on a Chromebook with Crostini, but that's still on the default image, which is Bullseye for now.  As far as I know we're getting the expected behaviour on all of those then.

I'm going to close this as I think the suggested fix is in the wrong direction.  We might need to consider some improvement in documenting usage.

**Closed by neilcsmith-net** 2023-08-07 11:21 UTC
